//! Versioned board-v2 regression corpus.
//!
//! The frozen cross-engine-board-v1 timing profile remains untouched. This
//! suite consumes identities, capture partitions, canonical FENs, perft and
//! divides generated by python-chess, then proves Rarog's incremental state
//! survives normal/hinted make, staged generation, null moves, cloning and
//! full unwind. It is deliberately outside every timed benchmark.

use std::collections::{BTreeMap, BTreeSet};

use rarog::board::{Board, Color, MoveList, Piece};

const ORACLE: &str = include_str!("data/board-v2-oracle.tsv");
const REQUIRED_TAGS: &[&str] = &[
    "single-check",
    "double-check",
    "evasion",
    "ep-legal",
    "ep-illegal",
    "quiet-promotion",
    "capture-promotion",
    "underpromotion",
    "castle-white-king",
    "castle-white-queen",
    "castle-black-king",
    "castle-black-queen",
    "sparse-endgame",
    "long-history",
];

#[derive(Clone, Debug)]
struct Case {
    name: String,
    tags: BTreeSet<String>,
    fen: String,
    depth: u32,
    legal: BTreeSet<String>,
    captures: BTreeSet<String>,
    perft: u64,
    divide: BTreeMap<String, u64>,
}

fn cases() -> Vec<Case> {
    let mut rows = Vec::new();
    for line in ORACLE.lines().filter(|line| !line.starts_with('#')) {
        let fields: Vec<_> = line.split('|').collect();
        assert_eq!(
            fields.len(),
            8,
            "oracle row must contain eight fields: {line}"
        );
        let legal = move_set(fields[4]);
        let captures = move_set(fields[5]);
        let divide = fields[7]
            .split_whitespace()
            .map(|entry| {
                let (mv, nodes) = entry
                    .split_once(':')
                    .unwrap_or_else(|| panic!("bad divide entry {entry:?}"));
                (
                    mv.to_string(),
                    nodes
                        .parse::<u64>()
                        .unwrap_or_else(|_| panic!("bad divide count {nodes:?}")),
                )
            })
            .collect::<BTreeMap<_, _>>();
        assert_eq!(
            legal.len(),
            divide.len(),
            "{} duplicate or missing divide move",
            fields[0]
        );
        rows.push(Case {
            name: fields[0].to_string(),
            tags: fields[1].split(',').map(str::to_string).collect(),
            fen: fields[2].to_string(),
            depth: fields[3]
                .parse()
                .unwrap_or_else(|_| panic!("bad depth {:?}", fields[3])),
            legal,
            captures,
            perft: fields[6]
                .parse()
                .unwrap_or_else(|_| panic!("bad perft {:?}", fields[6])),
            divide,
        });
    }
    assert!(!rows.is_empty(), "board-v2 oracle is empty");
    assert_eq!(
        rows.iter()
            .map(|case| &case.name)
            .collect::<BTreeSet<_>>()
            .len(),
        rows.len(),
        "board-v2 case names must be unique"
    );
    rows
}

fn move_set(text: &str) -> BTreeSet<String> {
    text.split_whitespace().map(str::to_string).collect()
}

fn generated_set(moves: &MoveList) -> BTreeSet<String> {
    moves.iter().map(ToString::to_string).collect()
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct State {
    fen: String,
    hash: u64,
    pawn_key: u64,
    minor_key: u64,
    non_pawn_keys: [u64; 2],
    checkers: u64,
    all_occ: u64,
    pieces: [u64; 12],
}

impl State {
    fn of(board: &Board) -> Self {
        let mut pieces = [0; 12];
        for (index, slot) in pieces.iter_mut().enumerate() {
            let color = if index < 6 {
                Color::White
            } else {
                Color::Black
            };
            let piece = match index % 6 {
                0 => Piece::Pawn,
                1 => Piece::Knight,
                2 => Piece::Bishop,
                3 => Piece::Rook,
                4 => Piece::Queen,
                _ => Piece::King,
            };
            *slot = board.pieces(color, piece).0;
        }
        Self {
            fen: board.to_fen(),
            hash: board.hash,
            pawn_key: board.pawn_key(),
            minor_key: board.minor_key(),
            non_pawn_keys: [
                board.non_pawn_key(Color::White),
                board.non_pawn_key(Color::Black),
            ],
            checkers: board.checkers().0,
            all_occ: board.all_occ.0,
            pieces,
        }
    }

    fn assert_matches(&self, board: &Board, context: &str) {
        assert_eq!(Self::of(board), *self, "{context} changed board state");
        board
            .check_consistency()
            .unwrap_or_else(|error| panic!("{context} left board inconsistent: {error}"));
    }
}

fn divide(board: &mut Board, depth: u32) -> BTreeMap<String, u64> {
    let before = State::of(board);
    let mut result = BTreeMap::new();
    let moves = board.generate_legal_movelist();
    for &mv in &moves {
        board.make_move_unchecked(mv);
        let nodes = board.perft(depth - 1);
        board.unmake_move(mv);
        before.assert_matches(board, &format!("divide unmake {mv}"));
        result.insert(mv.to_string(), nodes);
    }
    result
}

fn assert_tags(case: &Case, board: &Board) {
    let generated = board.generate_legal_movelist();
    let moves = generated_set(&generated);
    if case.tags.contains("single-check") {
        assert_eq!(
            board.checkers().count(),
            1,
            "{} must have one checker",
            case.name
        );
    }
    if case.tags.contains("double-check") {
        assert_eq!(
            board.checkers().count(),
            2,
            "{} must have two checkers",
            case.name
        );
    }
    if case.tags.contains("evasion") {
        assert!(
            board.is_in_check() && !moves.is_empty(),
            "{} must exercise evasions",
            case.name
        );
    }
    if case.tags.contains("ep-legal") {
        assert!(
            moves.contains("e5d6"),
            "{} must contain legal EP",
            case.name
        );
    }
    if case.tags.contains("ep-illegal") {
        assert!(
            !moves.contains("b5c6"),
            "{} must reject pinned EP",
            case.name
        );
    }
    let promotions = moves.iter().filter(|mv| mv.len() == 5).collect::<Vec<_>>();
    if case.tags.contains("quiet-promotion") {
        assert!(
            promotions.iter().any(|mv| mv.starts_with("a7a8")),
            "{} needs quiet promotion",
            case.name
        );
    }
    if case.tags.contains("capture-promotion") {
        assert!(
            promotions.iter().any(|mv| mv.starts_with("a7b8")),
            "{} needs capture promotion",
            case.name
        );
    }
    if case.tags.contains("underpromotion") {
        for suffix in ['n', 'b', 'r'] {
            assert!(
                promotions.iter().any(|mv| mv.ends_with(suffix)),
                "{} missing underpromotion {suffix}",
                case.name
            );
        }
    }
    for (tag, mv) in [
        ("castle-white-king", "e1g1"),
        ("castle-white-queen", "e1c1"),
        ("castle-black-king", "e8g8"),
        ("castle-black-queen", "e8c8"),
    ] {
        if case.tags.contains(tag) {
            assert!(moves.contains(mv), "{} missing {mv}", case.name);
        }
    }
    if case.tags.contains("sparse-endgame") {
        assert!(board.all_occ.count() <= 10, "{} is not sparse", case.name);
    }
    if case.tags.contains("long-history") {
        assert!(
            board.halfmove_clock >= 90 && board.fullmove >= 100,
            "{} lacks long counters",
            case.name
        );
    }
}

/// Run the external-oracle checks as a single preflight.  The deliberately
/// corrupted cases below prove this checks board structure and work, rather
/// than merely finding a reassuring word in a fixture or comment.
fn preflight(case: &Case, board: &mut Board) -> Result<(), &'static str> {
    let before = State::of(board);
    if board.to_fen() != case.fen {
        return Err("canonical FEN");
    }
    if generated_set(&board.generate_legal_movelist()) != case.legal {
        return Err("legal identities");
    }
    if generated_set(&board.generate_legal_captures()) != case.captures {
        return Err("capture identities");
    }
    if board.perft(case.depth) != case.perft {
        return Err("perft work count");
    }
    if divide(board, case.depth) != case.divide {
        return Err("perft divide");
    }
    if State::of(board) != before {
        return Err("state restoration");
    }
    Ok(())
}

#[test]
fn board_v2_profile_is_complete_and_matches_independent_oracle() {
    let cases = cases();
    let present = cases
        .iter()
        .flat_map(|case| case.tags.iter().map(String::as_str))
        .collect::<BTreeSet<_>>();
    for tag in REQUIRED_TAGS {
        assert!(present.contains(tag), "profile lacks required tag {tag}");
    }

    for case in cases {
        let mut board = Board::from_fen(&case.fen)
            .unwrap_or_else(|error| panic!("{}: bad oracle FEN: {error}", case.name));
        assert_tags(&case, &board);
        preflight(&case, &mut board)
            .unwrap_or_else(|what| panic!("{} preflight failed: {what}", case.name));
    }
}

#[test]
fn board_v2_preflight_rejects_wrong_moves_work_and_state() {
    let case = cases()
        .into_iter()
        .find(|case| case.name == "ep-legal")
        .expect("ep-legal case must exist");

    let mut wrong_moves = case.clone();
    assert!(wrong_moves.legal.remove("e5d6"), "fixture move must exist");
    let mut board = Board::from_fen(&case.fen).expect("valid oracle FEN");
    assert_eq!(
        preflight(&wrong_moves, &mut board),
        Err("legal identities"),
        "preflight must reject a deliberately wrong legal-move identity"
    );

    let mut wrong_work = case.clone();
    wrong_work.perft += 1;
    let mut board = Board::from_fen(&case.fen).expect("valid oracle FEN");
    assert_eq!(
        preflight(&wrong_work, &mut board),
        Err("perft work count"),
        "preflight must reject a deliberately wrong work count"
    );

    let mut board = Board::from_fen(&case.fen).expect("valid oracle FEN");
    let mv = board.parse_move("e5d6").expect("legal en passant move");
    board.make_move_unchecked(mv);
    assert_eq!(
        preflight(&case, &mut board),
        Err("canonical FEN"),
        "preflight must reject a deliberately mutated board"
    );
}

#[test]
fn board_v2_normal_hinted_staged_and_null_paths_restore_every_field() {
    for case in cases() {
        let board =
            Board::from_fen(&case.fen).unwrap_or_else(|error| panic!("{}: {error}", case.name));
        let before = State::of(&board);
        let all = generated_set(&board.generate_legal_movelist());

        let mut staged = board.clone();
        let (captures, pinned) = staged.generate_legal_captures_pinned();
        let quiets = staged.generate_legal_quiets_pinned(pinned);
        let staged_moves: BTreeSet<String> = generated_set(&captures)
            .union(&generated_set(&quiets))
            .cloned()
            .collect();
        assert_eq!(staged_moves, all, "{} staged move paths differ", case.name);
        before.assert_matches(&staged, &format!("{} staged generation", case.name));

        let moves = board.generate_legal_movelist();
        for &mv in &moves {
            let gives_check = board.gives_check(mv);
            let mut normal = board.clone();
            normal.make_move(mv);
            normal
                .check_consistency()
                .unwrap_or_else(|error| panic!("{} normal {mv}: {error}", case.name));
            let after_normal = State::of(&normal);
            normal.unmake_move(mv);
            before.assert_matches(&normal, &format!("{} normal unmake {mv}", case.name));

            let mut hinted = board.clone();
            hinted.make_move_with_check(mv, gives_check);
            assert_eq!(
                State::of(&hinted),
                after_normal,
                "{} hinted {mv} differs",
                case.name
            );
            hinted.unmake_move(mv);
            before.assert_matches(&hinted, &format!("{} hinted unmake {mv}", case.name));
        }

        if !board.is_in_check() {
            let mut null_board = board.clone();
            null_board.make_null_move();
            null_board
                .check_consistency()
                .unwrap_or_else(|error| panic!("{} null make: {error}", case.name));
            null_board.unmake_null_move();
            before.assert_matches(&null_board, &format!("{} null roundtrip", case.name));
        }
    }
}

#[test]
fn board_v2_randomized_unwind_and_clone_history_are_independent() {
    let mut board =
        Board::from_fen("8/8/8/8/8/8/8/K5k1 w - - 0 143").expect("valid long-history root");
    let root = State::of(&board);
    let cycle = ["a1a2", "g1g2", "a2a1", "g2g1"];
    let mut played = Vec::new();
    for ply in 0..600 {
        let mv = board
            .parse_move(cycle[ply % cycle.len()])
            .expect("reversible move must stay legal");
        played.push(mv);
        board.make_move_unchecked(mv);
        board
            .check_consistency()
            .expect("long history must remain consistent");
    }

    let mut clone = board.clone();
    let clone_state = State::of(&clone);
    let clone_move = *clone
        .generate_legal_movelist()
        .iter()
        .next()
        .expect("clone must have a legal move");
    clone.make_move_unchecked(clone_move);
    assert_ne!(State::of(&clone), clone_state, "clone move must be live");
    assert_eq!(
        State::of(&board),
        clone_state,
        "clone mutation leaked to source board"
    );
    clone.unmake_move(clone_move);
    clone_state.assert_matches(&clone, "clone unmake");

    while let Some(mv) = played.pop() {
        board.unmake_move(mv);
        board
            .check_consistency()
            .expect("randomized unwind must remain consistent");
    }
    root.assert_matches(&board, "long-history complete unwind");
}
