#!/usr/bin/env python3
"""Generate and verify the independent board-v2 legal-move oracle.

The profile deliberately stays outside the historical cross-engine-board-v1
benchmark. python-chess supplies legal move identities, capture partition,
canonical FEN, perft and divide values. Rust tests consume the generated file;
this script verifies that its source is still independently reproducible.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import chess


ROOT = Path(__file__).resolve().parents[2]
PROFILE = ROOT / "tests" / "data" / "board-v2.tsv"
DEFAULT_OUTPUT = ROOT / "tests" / "data" / "board-v2-oracle.tsv"
REQUIRED_TAGS = {
    "single-check",
    "double-check",
    "evasion",
    "ep-legal",
    "ep-illegal",
    "quiet-promotion",
    "capture-promotion",
    "underpromotion",
    "castle-white-king",
    "castle-white-queen",
    "castle-black-king",
    "castle-black-queen",
    "sparse-endgame",
    "long-history",
}


def load_profile(path: Path) -> list[tuple[str, set[str], str, int]]:
    rows = []
    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not raw or raw.startswith("#"):
            continue
        fields = raw.split("|")
        if len(fields) != 4:
            raise ValueError(f"{path}:{line_number}: expected four pipe-separated fields")
        name, tags_text, fen, depth_text = (field.strip() for field in fields)
        tags = set(tags_text.split(","))
        if not name or not tags or not fen:
            raise ValueError(f"{path}:{line_number}: empty required field")
        rows.append((name, tags, fen, int(depth_text)))
    if not rows:
        raise ValueError("profile is empty")
    if len({name for name, _, _, _ in rows}) != len(rows):
        raise ValueError("profile names must be unique")
    present = set().union(*(tags for _, tags, _, _ in rows))
    missing = REQUIRED_TAGS - present
    if missing:
        raise ValueError(f"profile lacks required coverage tags: {sorted(missing)}")
    return rows


def perft(board: chess.Board, depth: int) -> int:
    if depth == 0:
        return 1
    return sum(perft_after(board, move, depth - 1) for move in board.legal_moves)


def perft_after(board: chess.Board, move: chess.Move, depth: int) -> int:
    board.push(move)
    try:
        return perft(board, depth)
    finally:
        board.pop()


def require_profile_semantics(name: str, tags: set[str], board: chess.Board) -> None:
    checkers = len(board.attackers(not board.turn, board.king(board.turn)))
    legal = list(board.legal_moves)
    if "single-check" in tags and checkers != 1:
        raise ValueError(f"{name}: expected one checker, found {checkers}")
    if "double-check" in tags and checkers != 2:
        raise ValueError(f"{name}: expected two checkers, found {checkers}")
    if "evasion" in tags and (not board.is_check() or not legal):
        raise ValueError(f"{name}: expected a nonempty evasion set")
    ep_moves = [move for move in legal if board.is_en_passant(move)]
    if "ep-legal" in tags and not ep_moves:
        raise ValueError(f"{name}: expected a legal en-passant move")
    if "ep-illegal" in tags and (board.ep_square is None or ep_moves):
        raise ValueError(f"{name}: expected an EP square with no legal EP move")
    promotions = [move for move in legal if move.promotion]
    underpromotions = [move for move in promotions if move.promotion != chess.QUEEN]
    if "quiet-promotion" in tags and not any(not board.is_capture(move) for move in promotions):
        raise ValueError(f"{name}: expected a quiet promotion")
    if "capture-promotion" in tags and not any(board.is_capture(move) for move in promotions):
        raise ValueError(f"{name}: expected a capture promotion")
    if "underpromotion" in tags and len(underpromotions) < 3:
        raise ValueError(f"{name}: expected knight, bishop and rook underpromotions")
    castles = {move.uci() for move in legal if board.is_castling(move)}
    required_castles = {
        "castle-white-king": "e1g1",
        "castle-white-queen": "e1c1",
        "castle-black-king": "e8g8",
        "castle-black-queen": "e8c8",
    }
    for tag, move in required_castles.items():
        if tag in tags and move not in castles:
            raise ValueError(f"{name}: expected castling move {move}")
    if "sparse-endgame" in tags and len(board.piece_map()) > 10:
        raise ValueError(f"{name}: expected at most ten pieces")
    if "long-history" in tags and (board.halfmove_clock < 90 or board.fullmove_number < 100):
        raise ValueError(f"{name}: expected long-clock history state")


def render(rows: list[tuple[str, set[str], str, int]]) -> str:
    output = ["# board-v2-oracle-v1; generated by tools/diag/board_v2_oracle.py"]
    for name, tags, fen, depth in rows:
        board = chess.Board(fen)
        require_profile_semantics(name, tags, board)
        legal = sorted(move.uci() for move in board.legal_moves)
        captures = sorted(move.uci() for move in board.legal_moves if board.is_capture(move))
        divide = []
        for move in board.legal_moves:
            divide.append((move.uci(), perft_after(board, move, depth - 1)))
        divide.sort()
        output.append(
            "|".join(
                (
                    name,
                    ",".join(sorted(tags)),
                    board.fen(en_passant="legal"),
                    str(depth),
                    " ".join(legal),
                    " ".join(captures),
                    str(sum(nodes for _, nodes in divide)),
                    " ".join(f"{move}:{nodes}" for move, nodes in divide),
                )
            )
        )
    return "\n".join(output) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if output differs")
    args = parser.parse_args()
    expected = render(load_profile(PROFILE))
    if args.check:
        actual = args.output.read_text(encoding="utf-8")
        if actual != expected:
            raise SystemExit(f"{args.output} is stale; regenerate with this script")
        print(f"board-v2 oracle: PASS ({len(expected.splitlines()) - 1} cases)")
        return
    args.output.write_text(expected, encoding="utf-8")
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
