#!/usr/bin/env python3
"""Opposite-coloured-bishop scale screen: does a refit of Rarog's OCB scale
rule predict game outcomes better, with the rest of the evaluation fixed?

Rarog scales the whole tapered score by `s / 48` whenever each side has
exactly one bishop and the two stand on opposite colours, whatever else is on
the board, with `s = min(32 + 4 * pawns + 4 * passers, 48)` (pawns and passed
pawns of both sides). This tool reads that rule against outcome labels at the
static layer. It ranks candidates and accepts nothing.

Inputs are `rarog-texel --dump-scores <csv> <out> --scale` files: one
`fen;label;white-POV score;engine scale` row per position, the scale being
`linear_delta_scale` (the endgame factor times the texel-only rule-50 factor
`(199 - min(clock, 100)) / 199`). Because the engine's own factor is in the
file, the offline model of the rule is checked against the engine on every
row (`verify`) before any loss is computed from it.

  census    cohort sizes and pawn counts per file; reads no labels
  verify    the offline OCB rule reproduces the engine's factor on every row
  analyse   fit candidate rules on the training file, read them on the
            held-out file (paired squared-error gains, K fixed)
  drawn     static read on Syzygy-labelled OCB positions of six men or fewer,
            generated by `endgame_truth.py`'s generator: overclaim on draws
            and underclaim on wins, head rule against a candidate rule

Loss is the tuner's: `(label - 1 / (1 + exp(-K * score / 400)))^2`, K fixed.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

import numpy as np

OCB_NORMAL = 48

# Cohort codes.
NOT_OCB, PURE, PIECES, PAWNLESS = 0, 1, 2, 3
COHORT_NAMES = {PURE: "pure", PIECES: "pieces", PAWNLESS: "pawnless"}


def parse_board(fen: str):
    """Piece placement as {(file, rank): char}, rank 0 = White's back rank."""
    placement = fen.split(" ", 1)[0]
    squares = {}
    for row_index, row in enumerate(placement.split("/")):
        rank = 7 - row_index
        file = 0
        for ch in row:
            if ch.isdigit():
                file += int(ch)
            else:
                squares[(file, rank)] = ch
                file += 1
    return squares


def halfmove_clock(fen: str) -> int:
    fields = fen.split()
    return int(fields[4]) if len(fields) > 4 else 0


def passers_by_side(squares) -> tuple[int, int]:
    """Passed pawns of White and Black: no enemy pawn ahead on the same or an
    adjacent file (Rarog's `PASSED_PAWN_MASKS`)."""
    white = [sq for sq, ch in squares.items() if ch == "P"]
    black = [sq for sq, ch in squares.items() if ch == "p"]
    w = sum(
        1 for f, r in white
        if not any(abs(bf - f) <= 1 and br > r for bf, br in black)
    )
    b = sum(
        1 for f, r in black
        if not any(abs(wf - f) <= 1 and wr < r for wf, wr in white)
    )
    return w, b


def classify(fen: str):
    """(cohort, pawns, passers_white, passers_black, engine_ocb_scale or None).

    `engine_ocb_scale` is the `/48` value Rarog's dispatch applies to this
    row, including the specialised pawnless draws that pre-empt it; None when
    the OCB rule does not apply.
    """
    placement = fen.split(" ", 1)[0]
    if placement.count("B") != 1 or placement.count("b") != 1:
        return NOT_OCB, 0, 0, 0, None
    squares = parse_board(fen)
    colours = {ch: (f + r) % 2 for (f, r), ch in squares.items() if ch in "Bb"}
    if colours["B"] == colours["b"]:
        return NOT_OCB, 0, 0, 0, None
    pawns = sum(1 for ch in squares.values() if ch in "Pp")
    others = [ch for ch in squares.values() if ch not in "KkPpBb"]
    if pawns == 0:
        majors = any(ch in "RrQq" for ch in others)
        white_minors = 1 + sum(1 for ch in others if ch == "N")
        black_minors = 1 + sum(1 for ch in others if ch == "n")
        if not majors and white_minors == 1 and black_minors == 1:
            return PAWNLESS, 0, 0, 0, 0
        return PAWNLESS, 0, 0, 0, 32
    pw, pb = passers_by_side(squares)
    scale = min(32 + 4 * pawns + 4 * (pw + pb), OCB_NORMAL)
    return (PURE if not others else PIECES), pawns, pw, pb, scale


def rule50_factor(fen: str) -> float:
    return (199.0 - min(halfmove_clock(fen), 100)) / 199.0


def read_dump(path: Path):
    """Yield (fen, label, score, engine_scale) from a `--scale` dump."""
    with path.open() as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            fen, label, score, scale = line.split(";")
            yield fen, float(label), int(score), float(scale)


def men(fen: str) -> int:
    return sum(1 for ch in fen.split(" ", 1)[0] if ch.isalpha())


def material_key(fen: str) -> str:
    """`KBP-KB` style, White first, pieces in Q R B N P order."""
    placement = fen.split(" ", 1)[0]
    sides = []
    for pieces in ("QRBNP", "qrbnp"):
        sides.append("K" + "".join(ch.upper() * placement.count(ch) for ch in pieces))
    return "-".join(sides)


def cmd_verify(args) -> int:
    """Every OCB row: the engine's factor equals the offline rule's. Every
    other row: the engine's factor is the rule-50 factor alone, except
    specialised material of five men or fewer."""
    checked = mismatched = special = 0
    special_max_men = 0
    worst = []
    for path in args.dumps:
        for fen, _label, _score, engine in read_dump(path):
            cohort, _p, _w, _b, ocb = classify(fen)
            r50 = rule50_factor(fen)
            checked += 1
            if ocb is not None:
                expected = ocb / OCB_NORMAL * r50
                if abs(engine - expected) > 1e-12:
                    mismatched += 1
                    if len(worst) < 10:
                        worst.append((fen, engine, expected))
            elif abs(engine - r50) > 1e-12:
                special += 1
                special_max_men = max(special_max_men, men(fen))
    ok = mismatched == 0 and special_max_men <= 5
    print(json.dumps({
        "rows": checked,
        "ocb_mismatches": mismatched,
        "non_ocb_rows_with_another_factor": special,
        "their_max_men": special_max_men,
        "examples": worst,
        "pass": ok,
    }, indent=2))
    return 0 if ok else 1


def load_cohorts(path: Path):
    """Arrays for the OCB rows with pawns, plus the file's global loss terms."""
    rows = {"cohort": [], "pawns": [], "pw": [], "pb": [], "s0": [],
            "score": [], "label": []}
    all_scores, all_labels = [], []
    for fen, label, score, _engine in read_dump(path):
        all_scores.append(score)
        all_labels.append(label)
        cohort, pawns, pw, pb, ocb = classify(fen)
        if cohort not in (PURE, PIECES):
            continue
        rows["cohort"].append(cohort)
        rows["pawns"].append(pawns)
        rows["pw"].append(pw)
        rows["pb"].append(pb)
        rows["s0"].append(ocb)
        rows["score"].append(score)
        rows["label"].append(label)
    arrays = {k: np.array(v) for k, v in rows.items()}
    # Recover the unscaled integer score: the engine computes
    # trunc(raw * s0 / 48); at s0 = 48 the dump is exact, below it the
    # interval midpoint is within 1.5 cp.
    s0 = arrays["s0"].astype(float)
    score = arrays["score"].astype(float)
    raw = np.where(
        s0 == OCB_NORMAL, score,
        np.round((score + 0.5 * np.sign(score)) * OCB_NORMAL / s0),
    )
    arrays["raw"] = raw
    return arrays, np.array(all_scores, float), np.array(all_labels, float)


def sigmoid(score, k):
    return 1.0 / (1.0 + np.exp(-k * score / 400.0))


def scaled(raw, s):
    """Rust's integer `raw * s / 48`, truncating toward zero."""
    return np.trunc(raw * s / OCB_NORMAL)


def strong_passers(arrays):
    """Passed pawns of the side the unscaled score favours (none at 0)."""
    raw = arrays["raw"]
    return np.where(raw > 0, arrays["pw"], np.where(raw < 0, arrays["pb"], 0))


def rule_scale(form, params, pawns, passers):
    a, b, c = params
    return np.clip(a + b * pawns + c * passers, 0, OCB_NORMAL)


def cell_losses(raw, label, pawns, passers, k):
    """Squared-error sum for every (pawns, passers) cell at every s in 0..48:
    the loss of any rule over these rows is a lookup and a sum."""
    table = {}
    for cell in set(zip(pawns.tolist(), passers.tolist())):
        mask = (pawns == cell[0]) & (passers == cell[1])
        r = raw[mask][None, :]
        y = label[mask][None, :]
        s = np.arange(OCB_NORMAL + 1, dtype=float)[:, None]
        pred = sigmoid(scaled(r, s), k)
        table[cell] = ((y - pred) ** 2).sum(axis=1)
    return table


def fit_rule(table, grid):
    best = None
    for a in grid["a"]:
        for b in grid["b"]:
            for c in grid["c"]:
                loss = 0.0
                for (p, q), row in table.items():
                    loss += row[int(min(max(a + b * p + c * q, 0), OCB_NORMAL))]
                if best is None or loss < best[0]:
                    best = (loss, (a, b, c))
    return best[1]


def paired(base_err, cand_err):
    diff = base_err - cand_err
    n = len(diff)
    mean_base = base_err.mean()
    gain = 100.0 * diff.mean() / mean_base
    se = 100.0 * diff.std(ddof=1) / math.sqrt(n) / mean_base if n > 1 else float("nan")
    return gain, se


def cmd_census(args) -> int:
    out = {}
    for path in args.dumps:
        counts = {name: 0 for name in COHORT_NAMES.values()}
        pawn_hist = {"pure": {}, "pieces": {}}
        total = 0
        for fen, _label, _score, _engine in read_dump(path):
            total += 1
            cohort, pawns, _w, _b, _ocb = classify(fen)
            if cohort == NOT_OCB:
                continue
            name = COHORT_NAMES[cohort]
            counts[name] += 1
            if name in pawn_hist:
                pawn_hist[name][pawns] = pawn_hist[name].get(pawns, 0) + 1
        out[str(path)] = {"rows": total, "cohorts": counts,
                          "pawns": {k: dict(sorted(v.items())) for k, v in pawn_hist.items()}}
    print(json.dumps(out, indent=2))
    return 0


def cmd_analyse(args) -> int:
    k = args.k
    grid = {"a": range(0, OCB_NORMAL + 1), "b": range(0, 13), "c": range(0, 13)}
    train, _, _ = load_cohorts(args.train)
    held, held_scores, held_labels = load_cohorts(args.held_out)
    global_err = (held_labels - sigmoid(held_scores, k)) ** 2
    report = {"k": k, "train": str(args.train), "held_out": str(args.held_out),
              "held_out_rows": int(len(held_labels)),
              "held_out_global_mse": float(global_err.mean()), "cohorts": {}}
    report["pure_min_pawns"] = args.pure_min_pawns
    for code, name in ((PURE, "pure"), (PIECES, "pieces")):
        tm = train["cohort"] == code
        hm = held["cohort"] == code
        if code == PURE:
            # A pure ending has 4 + pawns men, so `--pure-min-pawns 3` keeps
            # the pure rows of seven men or more.
            tm &= train["pawns"] >= args.pure_min_pawns
            hm &= held["pawns"] >= args.pure_min_pawns
        t = {key: v[tm] for key, v in train.items()}
        h = {key: v[hm] for key, v in held.items()}
        h_err0 = (h["label"] - sigmoid(scaled(h["raw"], h["s0"]), k)) ** 2
        entry = {"train_rows": int(tm.sum()), "held_out_rows": int(hm.sum()),
                 "held_out_mse_head": float(h_err0.mean()), "forms": {}}
        forms = {
            "F1_total_passers": (t["pawns"], t["pw"] + t["pb"],
                                 h["pawns"], h["pw"] + h["pb"]),
            "F2_strong_passers": (t["pawns"], strong_passers(t),
                                  h["pawns"], strong_passers(h)),
        }
        for form, (tp, tq, hp, hq) in forms.items():
            table = cell_losses(t["raw"], t["label"], tp, tq, k)
            params = fit_rule(table, grid)
            s = rule_scale(form, params, hp, hq)
            err = (h["label"] - sigmoid(scaled(h["raw"], s), k)) ** 2
            gain, se = paired(h_err0, err)
            entry["forms"][form] = {
                "params_a_b_c": list(params),
                "held_out_gain_pct": round(gain, 3),
                "held_out_se_pct": round(se, 3),
                "global_gain_pct": round(100.0 * (h_err0 - err).sum() / global_err.sum(), 4),
                "mean_s": round(float(s.mean()), 2),
                "_err": err,
            }
        none_err = (h["label"] - sigmoid(h["raw"], k)) ** 2
        gain, se = paired(h_err0, none_err)
        entry["no_scaling"] = {"held_out_gain_pct": round(gain, 3),
                               "held_out_se_pct": round(se, 3)}
        f1 = entry["forms"]["F1_total_passers"].pop("_err")
        f2 = entry["forms"]["F2_strong_passers"].pop("_err")
        gain, se = paired(f1, f2)
        entry["F2_over_F1"] = {"gain_pct_of_F1": round(gain, 3), "se_pct": round(se, 3)}
        entry["head_mean_s"] = round(float(h["s0"].mean()), 2)
        entry["mean_label_strong"] = round(float(np.where(
            h["raw"] >= 0, h["label"], 1 - h["label"]).mean()), 4)
        report["cohorts"][name] = entry
    text = json.dumps(report, indent=2)
    print(text)
    if args.output:
        args.output.write_text(text + "\n")
    return 0


def cmd_drawn(args) -> int:
    """Write Syzygy-labelled OCB positions as a `FEN;label` file for the
    tuner's dump (`--emit`), or read a dump of them (`--dump`)."""
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import chess
    import chess.syzygy
    from endgame_truth import generate_family, parse_family, wdl_for_white

    if args.emit:
        tb = chess.syzygy.open_tablebase(str(args.syzygy))
        lines = []
        for name in args.families.split(","):
            strong, weak = parse_family(name)
            for board in generate_family(args.seed, name, strong, weak, args.positions):
                cohort, *_ = classify(board.fen())
                if cohort not in (PURE, PIECES):
                    continue
                wdl = wdl_for_white(tb, board)
                label = {2: "1", -2: "0"}.get(wdl, "0.5")
                lines.append(f"{board.fen()};{label}")
        tb.close()
        args.emit.write_text("\n".join(lines) + "\n")
        print(f"{len(lines)} OCB positions written to {args.emit}")
        return 0

    params = tuple(int(x) for x in args.candidate.split(","))
    form = args.form
    rows = list(read_dump(args.dump))
    by_family = {}
    for fen, label, score, _engine in rows:
        cohort, pawns, pw, pb, s0 = classify(fen)
        raw = score if s0 == OCB_NORMAL else round((score + 0.5 * math.copysign(1, score)) * OCB_NORMAL / s0) if score else 0
        if form == "F2_strong_passers":
            q = pw if raw > 0 else pb if raw < 0 else 0
        else:
            q = pw + pb
        s1 = int(min(max(params[0] + params[1] * pawns + params[2] * q, 0), OCB_NORMAL))
        cand = int(math.trunc(raw * s1 / OCB_NORMAL))
        # Generated positions put the strong side on White.
        key = material_key(fen)
        fam = by_family.setdefault(key, {"draws": 0, "head_over": 0, "cand_over": 0,
                                         "wins": 0, "head_under": 0, "cand_under": 0,
                                         "losses": 0})
        if label == 0.0:
            fam["losses"] += 1
        if label == 0.5:
            fam["draws"] += 1
            fam["head_over"] += score > args.threshold
            fam["cand_over"] += cand > args.threshold
        elif label == 1.0:
            fam["wins"] += 1
            fam["head_under"] += score < args.threshold
            fam["cand_under"] += cand < args.threshold
    print(json.dumps({"threshold_cp": args.threshold, "candidate": list(params),
                      "form": form, "by_men": by_family}, indent=2))
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    for name in ("census", "verify"):
        p = sub.add_parser(name)
        p.add_argument("dumps", nargs="+", type=Path)
    p = sub.add_parser("analyse")
    p.add_argument("--train", required=True, type=Path)
    p.add_argument("--held-out", required=True, type=Path)
    p.add_argument("--k", required=True, type=float)
    p.add_argument("--pure-min-pawns", type=int, default=1,
                   help="restrict the pure cohort to rows with at least this many pawns")
    p.add_argument("--output", type=Path)
    p = sub.add_parser("drawn")
    p.add_argument("--families", default="KBP-KB,KBPP-KB,KBP-KBP")
    p.add_argument("--positions", type=int, default=2000)
    p.add_argument("--seed", type=int, default=0x5E9D18)
    p.add_argument("--syzygy", type=Path)
    p.add_argument("--emit", type=Path)
    p.add_argument("--dump", type=Path)
    p.add_argument("--candidate", default="32,4,4")
    p.add_argument("--form", default="F1_total_passers")
    p.add_argument("--threshold", type=int, default=100)
    args = ap.parse_args()
    return {"census": cmd_census, "verify": cmd_verify,
            "analyse": cmd_analyse, "drawn": cmd_drawn}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
