"""Convert a registered SPSA surface to a Colosseum tune file.

`tools/spsa_configs/config_<group>.json` states each coordinate's engine default,
range and `step`, where `step` is the perturbation at the START of a weather-factory
run. Colosseum's tune file states `c_end`, the perturbation at the END of the
horizon, so the two differ by that run's own decay:

    c_end = step * N ** -gamma          gamma = 0.102, as tools/spsa.ps1 derives it

The horizon therefore belongs to the conversion and must match the registration:
the same surface at N = 5,000 and at N = 10,000 is not the same experiment.

    python tools/spsa_config_to_colosseum.py b23core --iterations 5000
    python tools/spsa_config_to_colosseum.py b23core --iterations 5000 --check

Writes (or checks) `tools/spsa_configs/colosseum/<group>.tune.toml`, the ordered
parameter vector, and `<group>.run.toml`, a run file that extends the tune policy
and applies `fixed_<group>.json` as fixed options on both arms.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

GAMMA = 0.102
ROOT = pathlib.Path(__file__).resolve().parent
CONFIGS = ROOT / "spsa_configs"
OUT = CONFIGS / "colosseum"


def tune_file(group: str, surface: dict, iterations: int) -> str:
    decay = iterations ** -GAMMA
    lines = [
        f"# Generated by tools/spsa_config_to_colosseum.py from config_{group}.json",
        f"# at N = {iterations} iterations; c_end = step * N ** -{GAMMA}.",
        "# Regenerate rather than edit: --check fails when the two disagree.",
    ]
    for name, spec in surface.items():
        c_end = spec["step"] * decay
        lines += [
            "",
            "[[parameters]]",
            f'name = "{name}"',
            f"initial = {spec['value']}",
            f"min = {spec['min_value']}",
            f"max = {spec['max_value']}",
            f"c_end = {c_end:.4f}",
        ]
    return "\n".join(lines) + "\n"


def run_file(group: str, fixed: dict, iterations: int) -> str:
    options = ", ".join(f'"{name}={value}"' for name, value in fixed.items())
    return (
        f"# Generated by tools/spsa_config_to_colosseum.py from fixed_{group}.json.\n"
        f"# The surface is config_{group}.json converted at N = {iterations}.\n"
        "# Supply the engine, --total-games, --seed and --dir on the command line.\n"
        "\n"
        'extend = "../../colosseum/spsa-tune.toml"\n'
        'unset = ["/options/option"]\n'
        "\n"
        "[options]\n"
        f'tune = "{group}.tune.toml"\n'
        f"option = [{options}]\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("group", help="surface name, as in config_<group>.json")
    parser.add_argument("--iterations", type=int, required=True, help="registered horizon N")
    parser.add_argument("--check", action="store_true", help="compare instead of writing")
    args = parser.parse_args()

    if args.iterations < 1:
        parser.error("--iterations must be positive")
    surface_path = CONFIGS / f"config_{args.group}.json"
    fixed_path = CONFIGS / f"fixed_{args.group}.json"
    if not surface_path.is_file():
        parser.error(f"no surface at {surface_path}")
    surface = json.loads(surface_path.read_text(encoding="utf-8"))
    fixed = json.loads(fixed_path.read_text(encoding="utf-8")) if fixed_path.is_file() else {}

    written = {
        OUT / f"{args.group}.tune.toml": tune_file(args.group, surface, args.iterations),
        OUT / f"{args.group}.run.toml": run_file(args.group, fixed, args.iterations),
    }
    if args.check:
        stale = [
            path
            for path, want in written.items()
            if not path.is_file() or path.read_text(encoding="utf-8").replace("\r\n", "\n") != want
        ]
        for path in stale:
            print(f"stale or missing: {path}", file=sys.stderr)
        if stale:
            return 1
        print(f"{len(written)} files current for {args.group} at N = {args.iterations}")
        return 0

    OUT.mkdir(parents=True, exist_ok=True)
    for path, text in written.items():
        # The tree is CRLF; newline='' keeps the text exactly as written.
        path.write_text(text.replace("\n", "\r\n"), encoding="utf-8", newline="")
        print(f"wrote {path} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
